version: 2
#  Copyright (C) 2018-2022 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.
# 

# Configuration file for Circle CI 
# CI will report failure if any executed command returns and error status
# Operations performed are as follows
# Build source code
# Run unit tests for C++ and Java
# Run static code analyzer for SourceCloud
# Upload test results
# Every run command should start with source ${INIT_ENV} to ensure all default dependancies are available
jobs:
  build:
    # Pull docker image 
    # XTERM used for better make output        
    docker:
      - image: cimg/python:3.8.10-node
    environment:
      TERM: xterm  
    parallelism: 1  
    resource_class: medium
    working_directory: "metrics" 
    steps:
      #setup remote docker
      - setup_remote_docker :
          docker_layer_caching: false
      - run: git clone -b develop https://github.com/usdot-fhwa-stol/github_metrics.git
      - run: 
         name: install Deps
         command: |
           set -x
           sudo apt-get update -y && sudo apt-get upgrade -y          
           sudo apt-get install sudo -y
           sudo apt-get install git wget tar npm -y
           sudo apt-get -y -qq update
           sudo apt-get -y install build-essential checkinstall
           sudo apt-get -y install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev
           sudo apt install python3.8 -y
           sudo apt install python3-pip -y
      - run:
          name: Copy env.example and RUN metrics
          command: |
            ls -la
            pwd
            cd /home/circleci/project/metrics/github_metrics/code-gov/code-gov-repo-metrics/
            #cd /home/circleci/project/metrics/github_metrics/code-gov/code-gov-github-metrics/code-gov-repo-metrics
            ls -la
            pwd
            cp .env.example .env
            cat .env
            cat config.json
            npm install dotenv
            npm audit fix
            npm fund
            #npm run start 2022-06-01 2022-06-31
      - run:
          name: create virtual env and Run Metrics
          command: |
            pwd 
            ls -la
            cd /home/circleci/project/metrics/github_metrics/traffic-metrics
            ls -la   
            sudo apt-get -y install python3-venv
            python3 -m venv my-project-env
            source my-project-env/bin/activate
            pip install pandas 
            sudo pip install --upgrade pip
            python3 -m pip install --upgrade pip
            python -m pip install tensorflow
            python3 -m pip install pygithub
            pip install -r requirements.txt 
            pip install pandas 
            python3 github_metrics.py -t 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 -o usdot-fhwa-stol
            python3 github_metrics.py -t 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 -o usdot-fhwa-OPS
            python3 github_metrics.py -t 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 -o usdot-jpo-ode
            python3 export_traffic.py -t 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 -o usdot-fhwa-stol
            python3 export_traffic.py -t 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 -o usdot-fhwa-OPS
            python3 export_traffic.py -t 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 -o usdot-jpo-ode
            ls -la
            pwd
workflows:
  version: 2
  build:
    jobs:
      - build
